### ISSUE TITLE
Optimization fonction buy

### ISSUE THREAD

**Issue by TempTemp13928** [AyoubNabil/AmPr#1]
-trop de répétition de la variable **stock**
-lecture pas assez simplifie
-trop de condition
-refaire l'architecture de la fonction

**Comment by TempTemp13928** [comment]
actual code 
![image](https://github.com/AyoubNabil/AmPr/assets/143638399/93218438-e37c-477a-97f6-90c732ee0abf)
![image](https://github.com/AyoubNabil/AmPr/assets/143638399/c792a869-a175-4678-89b6-3c218723a613)

**Comment by AyoubNabil** [comment]
**New code :** 
![image](https://github.com/AyoubNabil/AmPr/assets/143638399/d9e277c4-caa9-467c-af57-acc7543e8172)

**Comment by TempTemp13928** [comment]
new code ****
![image](https://github.com/AyoubNabil/AmPr/assets/143638399/803722ec-2fef-47cb-8a87-f33498ea490e)

**Comment by TempTemp13928** [comment]
currentMoneyType not priceType + deleted print debug

**Comment by TempTemp13928** [comment]
**code updated** 
![image](https://github.com/AyoubNabil/AmPr/assets/143638399/3d2123b8-b645-46c2-8dd1-5555566f47da)
